# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoPasswordGenerator < Formula
  desc "A simple go app to generate password containing random string"
  homepage "https://github.com/rishi-suresh-keshav/go-password-generator"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rishi-suresh-keshav/go-password-generator/releases/download/v0.0.3/go-password-generator_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "a7b400ca4e436151da59b96c8f72c1f6df58cbd0566d77befbe50d485913c59e"

      def install
        bin.install "go-password-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rishi-suresh-keshav/go-password-generator/releases/download/v0.0.3/go-password-generator_0.0.3_Linux_arm64.tar.gz"
      sha256 "47a5b24ae954ce6404abe187b65587451c3767587c82b3415763f97a468ed797"

      def install
        bin.install "go-password-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rishi-suresh-keshav/go-password-generator/releases/download/v0.0.3/go-password-generator_0.0.3_Linux_x86_64.tar.gz"
      sha256 "3ccf5899990d6f9f7cd6b434d085822e1946cb39ab360657a28801b7b168a494"

      def install
        bin.install "go-password-generator"
      end
    end
  end
end
